### ISSUE TITLE
Why my character moves in a world space even if it doesnot move in a video?

### ISSUE THREAD

**Issue by UserNameIsAlredyTaken** [robertjoosten/video2mocap#10]
What am I doing wrong?  
![yog_video](https://user-images.githubusercontent.com/26858905/76647046-006f9080-6597-11ea-8f53-7fa6408b38fd.gif)
![yog_amim](https://user-images.githubusercontent.com/26858905/76647053-02395400-6597-11ea-8b2d-b650f57fd38f.gif)

**Comment by Billyboyyy** [comment]
i think the root of the problem is that your camera is not stable.  Even the little that your camera is panning is probably messing the system up.  Try propping your camera up instead of having something hold it.  if that's not your video you could try opening it in something like imovie and using video stabilization.

EDIT I personally have been trying to get this to work for over a month.  When you first ran the script did you have to fix any errors?  If so, what did you do?

**Comment by billyboyfan** [comment]
if that's not your video you could try opening it in something like imovie and using video stabilization.

**Comment by UserNameIsAlredyTaken** [comment]
That's odd, considering that in the video person is shifting up, but in mocap he is shifting down.
I'll check this on some other videos and wright back.

**Comment by UserNameIsAlredyTaken** [comment]
So, this is what I'v got with perfectly stable camera  
![stable](https://user-images.githubusercontent.com/26858905/77746478-09983d00-702e-11ea-9b5a-536cf901e95c.gif)
![yoga2](https://user-images.githubusercontent.com/26858905/77746520-13ba3b80-702e-11ea-9020-28223b38b216.gif)  

I don't think, it's stabilization problem but I don't know what the problem it is.
Could it be problem with bounding boxes?

**Comment by UserNameIsAlredyTaken** [comment]
> i think the root of the problem is that your camera is not stable. Even the little that your camera is panning is probably messing the system up. Try propping your camera up instead of having something hold it. if that's not your video you could try opening it in something like imovie and using video stabilization.
> 
> EDIT I personally have been trying to get this to work for over a month. When you first ran the script did you have to fix any errors? If so, what did you do?

I had some problems:
https://github.com/robertjoosten/video2mocap/issues/9#issue-564790454
I had to download another version of ffmpeg since FFmpeg 20180630-9f0077c is not presented in its page https://ffmpeg.zeranoe.com/builds/win64/static/

**Comment by UserNameIsAlredyTaken** [comment]
I have an assumption, that character will move properly if you move the camera synchronously.
There is camera position data in Temp/hmr_data.json (if you set keep_temt to true). If I use this data to update camera position on each animation frame, the character will move properly. Am I right, @robertjoosten? Or this data should already have been used by maya to produce proper movement? As I searched in source files there is no usage of this data.

**Comment by Billyboyyy** [comment]
To be honest I think it might just be a limitation of this software.  Even in the demo there was so much spontaneous movement of the feet that the animation would be unusable in a game without extensive tweaking.  I have come to the conclusion that this tool is a cool demo but is unusable in its current state to produce any kind if game amimation.

I did however find a service that is alot further along called radicle motion .  It does unfortunetly cost 8$ a month but it looks great! 
https://getrad.co/

Also, you can download other people's motion capture data for free and I found a few animations that look similar to what your trying to create!

**Comment by robertjoosten** [comment]
Sorry for the delayed reply.
You are right it is a limitation of the software. My plan was to try and normalise this a bit on a per frame basis, but obviously that would be a stop gap. Technology has evolved since so you can have a look at this library: https://github.com/akanazawa/motion_reconstruction . It reconstructs from a video :). You'd miss out on the maya skeleton creation though.

**Comment by UserNameIsAlredyTaken** [comment]
Thank you for reply. I'll chek this.
